[env]
RUST_BACKTRACE = {unset = true}

[tasks.default]
dependencies = ["build"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.test]
command = "cargo"
args = ["test", "--", "--show-output"]
